from raytracing import *
from raytracing.edmund import *

# path = rt.OpticalPath()
# path.append(rt.Space(d=40))
# path.append(rt.Lens(f=40,diameter=25.4))
# path.append(rt.Space(d=240))
# path.append(rt.Lens(f=200,diameter=50.8))
# path.append(rt.Space(d=200))
# path.append(rt.Aperture(diameter=48))
# path.append(rt.Space(d=45))
# path.append(rt.Lens(f=45,diameter=48))
# path.append(rt.Space(d=90))
# path.append(rt.Lens(f=45,diameter=48))
# path.append(rt.Space(d=90))
# path.append(rt.Aperture(diameter=50))
# path.append(rt.Space(d=100))

# path = rt.OpticalPath()
# path.append(rt.Space(d=75))
# path.append(rt.Lens(f=75,diameter=50.8))
# path.append(rt.Space(d=75))
# path.append(rt.Lens(f=300,diameter=75))
# path.append(rt.Space(d=75))
# path.append(rt.Lens(f=200,diameter=75))
# path.append(rt.Space(d=107))
# path.append(rt.Aperture(diameter=48,label='Back Aperture'))
# path.append(rt.Space(d=45))
# path.append(rt.Lens(f=45,diameter=48,label='Obj'))
# path.append(rt.Space(d=90))
# path.append(rt.Lens(f=45,diameter=48,label='Obj'))
# path.append(rt.Space(d=90))
# path.append(rt.Aperture(diameter=50))
# path.append(rt.Space(d=100))

# path = rt.OpticalPath()
# path.append(rt.Space(d=100))
# path.append(rt.Lens(f=100,diameter=75))
# path.append(rt.Space(d=300))
# path.append(rt.Lens(f=200,diameter=75))
# path.append(rt.Space(d=200))
# path.append(rt.Aperture(diameter=48,label='Back Aperture'))
# path.append(rt.Space(d=45))
# path.append(rt.Lens(f=45,diameter=48,label='Obj'))
# path.append(rt.Space(d=90))
# path.append(rt.Lens(f=45,diameter=48,label='Obj'))
# path.append(rt.Space(d=45))
# path.append(rt.Aperture(diameter=50))
# path.append(rt.Space(d=100))

path = OpticalPath()
path.append(Space(d=100))
path.append(AC75_100())
path.append(Space(d=300))
path.append(AC75_200())
path.append(Space(d=200))

path.objectHeight = 23  # object height (full). FIXME: Python 2.7 requires 1.0, not 1 (float)
path.objectPosition = 0.0 # always at z=0 for now. FIXME: Python 2.7 requires 1.0, not 1 (float)
path.fanAngle = 0.5       # full fan angle for rays
path.fanNumber = 10       # number of rays in fan
path.rayNumber = 3

path.display()